### MONITORS ###
source = ~/.config/hypr/hyprland/monitors.conf
### MY PROGRAMS ###
source = ~/.config/hypr/hyprland/programs.conf
### AUTOSTART ###
source = ~/.config/hypr/hyprland/autostart.conf
### ENVIRONMENT VARIABLES ###
source = ~/.config/hypr/hyprland/environment.conf
### PERMISSIONS ###
source = ~/.config/hypr/hyprland/permission.conf
### LOOK AND FEEL ###
source = ~/.config/hypr/hyprland/lookandfeel.conf
### INPUT ###
source = ~/.config/hypr/hyprland/input.conf
### KEYBINDINGS ###
source = ~/.config/hypr/hyprland/bind.conf
### WINDOWS AND WORKSPACES ###
source = ~/.config/hypr/hyprland/windows.conf
